return {
PlaceObj('ModItemCommanderProfilePreset', {
	additional_colonists_per_rocket = -6,
	additional_initial_applicants = -25,
	additional_research_points = -100,
	anomaly_bonus_breakthrough = range(10, 5),
	challenge_mod = 50,
	comment = "Investigator",
	display_name = T(956392691604, --[[ModItemCommanderProfilePreset Default investigator display_name]] "Investigator"),
	effect = T(326461270231, --[[ModItemCommanderProfilePreset Default investigator effect]] "All your life, your passion has been knowledge - seeking out what nobody else knows, discovering the wonders of the universe. Mars is a logical next step: more mysteries, more discoveries, and tougher challenges."),
	group = "Default",
	id = "investigator",
	name = "investigator",
}),
PlaceObj('ModItemCommanderProfilePreset', {
	additional_colonists_per_rocket = -6,
	additional_initial_applicants = -25,
	additional_research_points = -100,
	challenge_mod = 50,
	comment = "Roboticist",
	display_name = T(564937702282, --[[ModItemCommanderProfilePreset Default roboticist display_name]] "Roboticist"),
	effect = T(863256343590, --[[ModItemCommanderProfilePreset Default roboticist effect]] "Designing and building robots all your life, you firmly believe that they have a place on Mars alongside humans. The humans, however, aren't so enthused about this..."),
	group = "Default",
	id = "roboticist",
	name = "investigator",
	tech1 = "DronePrinting",
	tech2 = "ThePositronicBrain",
	tech3 = "PrintedElectronics",
}),
PlaceObj('ModItemGameRules', {
	challenge_mod = -20,
	description = T(909534856040, --[[ModItemGameRules crop-shed description]] "Delve through the seed shed to find some things that might be worth growing."),
	display_name = T(289995570322, --[[ModItemGameRules crop-shed display_name]] "Crop Shed"),
	flavor = T(580199721104, --[[ModItemGameRules crop-shed flavor]] '"I\'ve no idea what this is. Doesn\'t look edible. Grow it anyway!"'),
	group = "Default",
	id = "crop-shed",
	PlaceObj('ModItemCropPreset', {
		CropEntity = "CropAlgae",
		Desc = T(--[[ModItemCropPreset biofuel Desc]] "Ethanol produced by dedicated biofuel crops"),
		DisplayName = T(--[[ModItemCropPreset biofuel DisplayName]] "Biofuel"),
		DisplayNamePlural = T(--[[ModItemCropPreset biofuel DisplayNamePlural]] "Biofuel"),
		FarmClass = "FarmHydroponic",
		FoodOutput = 30000,
		GrowthTime = 720000,
		InitialGrowthTime = 720000,
		OxygenProduction = 100,
		ResourceType = "Fuel",
		WaterDemand = 500,
		comment = "Biofuel",
		group = "Hydroponic Farm",
		id = "biofuel",
	}),
	PlaceObj('ModItemCropPreset', {
		CropEntity = "CropCabbageArm",
		Desc = T(395073404546, --[[ModItemCropPreset fibers Desc]] "Synthetic plastics have their place, but we can grow a nearly equivalent fiber."),
		DisplayName = T(640855815138, --[[ModItemCropPreset fibers DisplayName]] "Natural Fibers"),
		DisplayNamePlural = T(531882077142, --[[ModItemCropPreset fibers DisplayNamePlural]] "Natural Fibers"),
		FarmClass = "FarmHydroponic",
		GrowthTime = 720000,
		InitialGrowthTime = 720000,
		ResourceType = "Polymers",
		comment = "Natural Fibers",
		group = "Hydroponic Farm",
		id = "fibers",
	}),
	PlaceObj('ModItemCropPreset', {
		CropEntity = "CropRapeseed",
		Desc = T(739350427508, --[[ModItemCropPreset fibrous-leaf Desc]] "Tasteless, tough, and completely unappetizing, these plants have the saving grace that their tough fibers can be spun into natural plastics and their leaves will improve the soil for the next crop."),
		DisplayName = T(503892219066, --[[ModItemCropPreset fibrous-leaf DisplayName]] "Fibrous Leaf Plants"),
		DisplayNamePlural = T(204698953808, --[[ModItemCropPreset fibrous-leaf DisplayNamePlural]] "Fibrous Leaf Plants"),
		FarmClass = "FarmConventional",
		FoodOutput = 5000,
		GrowthTime = 360000,
		InitialGrowthTime = 720000,
		OxygenProduction = 100,
		ResourceType = "Polymers",
		SoilEffect = 75,
		comment = "Fibrous Leaf Plants",
		group = "Farm",
		icon = "UI/Icons/Buildings/crops_silk_trees.tga",
		id = "fibrous-leaf",
	}),
}),
PlaceObj('ModItemGameRules', {
	challenge_mod = -50,
	comment = "Tech Bootstrap",
	description = T(471790995116, --[[ModItemGameRules techstrap description]] "Take advantage of simulator research to get a head-start on Martian technology."),
	display_name = T(302777476836, --[[ModItemGameRules techstrap display_name]] "Tech Bootstrap"),
	flavor = T(474317680531, --[[ModItemGameRules techstrap flavor]] "The simulations may not be entirely accurate, but that doesn't make them useless!"),
	group = "Default",
	id = "techstrap",
	PlaceObj('Effect_GrantTech', {
		Field = "Biotech",
		Research = "HygroscopicVaporators",
	}),
	PlaceObj('Effect_GrantTech', {
		Field = "Engineering",
		Research = "LowGHighrise",
	}),
	PlaceObj('Effect_GrantTech', {
		Field = "Robotics",
		Research = "TransportOptimization",
	}),
	PlaceObj('Effect_GrantTech', {
		Field = "Physics",
		Research = "ExtractorAmplification",
	}),
	PlaceObj('Effect_GrantTech', {
		Field = "Social",
		Research = "EarthMarsInitiative",
	}),
	PlaceObj('Effect_GrantTech', {
		Field = "Terraforming",
		-- Technically this can't ever show up in slot 1, but I don't want to double up Martian Veg with the sponsor
		Research = "TerraformingRover",
	}),
	PlaceObj('Effect_GrantTech', {
		Field = "ReconAndExpansion",
		Research = "LowGShaftDigging",
	}),
}),
PlaceObj('ModItemGameRules', {
	challenge_mod = -50,
	comment = "International Trade",
	description = T(471790995115, --[[ModItemGameRules intl-trade description]] "Trade with other sponsors, allowing you to purchase their unique vehicles."),
	display_name = T(302777476835, --[[ModItemGameRules intl-trade display_name]] "International Trade"),
	flavor = T(474317680530, --[[ModItemGameRules intl-trade flavor]] '"Free trade is the key. Once you can control that, you can control anything."'),
	group = "Default",
	id = "intl-trade",
	PlaceObj('Effect_UnlockResupplyItem', {
		Item = "RCConstructor",
	}),
	PlaceObj('Effect_UnlockResupplyItem', {
		Item = "RCDriller",
	}),
	PlaceObj('Effect_UnlockResupplyItem', {
		Item = "RCSolar",
	}),
	PlaceObj('Effect_UnlockResupplyItem', {
		Item = "RCHarvester",
	}),
	PlaceObj('Effect_UnlockResupplyItem', {
		Item = "RCSensor",
	}),
}),
}
