-- ========== GENERATED BY CommanderProfilePreset Editor DO NOT EDIT MANUALLY! ==========

PlaceObj('ModItemCommanderProfilePreset', {
	additional_colonists_per_rocket = -6,
	additional_initial_applicants = -25,
	additional_research_points = -100,
	challenge_mod = 50,
	display_name = T(895862714725, --[[ModItemCommanderProfilePreset roboticist display_name]] "Roboticist"),
	effect = T(685263601027, --[[ModItemCommanderProfilePreset roboticist effect]] "Designing and building robots all your life, you firmly believe that they have a place on Mars alongside humans. The humans, however, aren't so enthused about this..."),
	group = "Default",
	id = "roboticist",
	mod_handle = 1,
	save_in = "Mod/qKwMjRQ",
	tech1 = "DronePrinting",
	tech2 = "ThePositronicBrain",
	tech3 = "PrintedElectronics",
	tech4 = "ServiceBots",
})

PlaceObj('ModItemCommanderProfilePreset', {
	anomaly_bonus_breakthrough = range(25, 25),
	anomaly_bonus_event = range(25, 25),
	anomaly_bonus_free_tech = range(25, 25),
	display_name = T(619012288476, --[[ModItemCommanderProfilePreset testcommander display_name]] "Test Commander"),
	effect = T(132335079788, --[[ModItemCommanderProfilePreset testcommander effect]] "Whatever I happen to be testing with at the moment. Not meant to be balanced or fair or anything."),
	group = "Default",
	id = "testcommander",
	mod_handle = 2,
	save_in = "Mod/qKwMjRQ",
})

