-- ========== GENERATED BY GameRuleDef Editor DO NOT EDIT MANUALLY! ==========

PlaceObj('ModItemGameRuleDef', {
	challenge_mod = -100,
	description = T(122269382025, --[[ModItemGameRuleDef common-thread description]] "Trail a thread behind you as you go to Mars. What could possibly go wrong?"),
	display_name = T(544731184979, --[[ModItemGameRuleDef common-thread display_name]] "Common Thread"),
	flavor_text = T(164495336648, --[[ModItemGameRuleDef common-thread flavor_text]] "There is a scarlet thread of commerce running through the tangled skein of life..."),
	group = "Default",
	id = "common-thread",
	mod_handle = 3,
	save_in = "Mod/qKwMjRQ",
	PlaceObj('Effect_GrantPrefab', {
		Prefab = "SpaceElevator",
	}),
	PlaceObj('Effect_ModifyLabel', {
		Label = "SpaceElevator",
		Percent = -100,
		Prop = "electricity_consumption",
	}),
	PlaceObj('Effect_ModifyLabel', {
		Label = "SpaceElevator",
		Percent = -100,
		Prop = "maintenance_resource_amount",
	}),
})

PlaceObj('ModItemGameRuleDef', {
	SortKey = 2,
	challenge_mod = -50,
	description = T(165780324313, --[[ModItemGameRuleDef poweruser description]] "Following in the footsteps of Nikola Tesla, you try your best to use electricity in ways it's never before been used!"),
	display_name = T(287643487882, --[[ModItemGameRuleDef poweruser display_name]] "Power User"),
	group = "Default",
	id = "poweruser",
	mod_handle = 4,
	save_in = "Mod/qKwMjRQ",
	PlaceObj('Effect_UnlockUpgrade', {
		Upgrade = "FusionReactor_EternalFusion",
	}),
	PlaceObj('Effect_ModifyLabel', {
		Amount = 16,
		Label = "Consts",
		Prop = "ElectricityForResearchPoint",
	}),
	PlaceObj('Effect_GrantTech', {
		Field = "Breakthroughs",
		Research = "SuperiorCables",
	}),
	PlaceObj('Effect_GrantTech', {
		Field = "ReconAndExpansion",
		Research = "SignalBoosters",
	}),
})

PlaceObj('ModItemGameRuleDef', {
	SortKey = 3,
	challenge_mod = -25,
	description = T(368671976932, --[[ModItemGameRuleDef intl-trade description]] "Trade with other sponsors, allowing you to purchase their unique vehicles."),
	display_name = T(650940583060, --[[ModItemGameRuleDef intl-trade display_name]] "International Trade"),
	flavor_text = T(215847288024, --[[ModItemGameRuleDef intl-trade flavor_text]] "Free trade is the key. Once you can control that, you can control anything."),
	group = "Default",
	id = "intl-trade",
	mod_handle = 5,
	save_in = "Mod/qKwMjRQ",
	PlaceObj('Effect_GrantTech', {
		Field = "Breakthroughs",
		Research = "GlobalSupport",
	}),
})

PlaceObj('ModItemGameRuleDef', {
	SortKey = 5,
	challenge_mod = -100,
	description = T(101322990601, --[[ModItemGameRuleDef infra description]] "A Mars colony depends on good infrastructure. Begin with an experimental dome design."),
	display_name = T(895951355458, --[[ModItemGameRuleDef infra display_name]] "Infrastructure"),
	group = "Default",
	id = "infra",
	mod_handle = 6,
	save_in = "Mod/qKwMjRQ",
	PlaceObj('Effect_GrantTech', {
		Field = "ReconAndExpansion",
		Research = "PrefabRefab",
	}),
	PlaceObj('Effect_GrantTech', {
		Field = "Engineering",
		Research = "AdvancedMartianEngines",
	}),
	PlaceObj('Effect_GrantTech', {
		Field = "Physics",
		Research = "DeepScanning",
	}),
	PlaceObj('Effect_GrantPrefab', {
		Prefab = "DomeDiamond",
	}),
	PlaceObj('Effect_ModifyLabel', {
		Label = "DroneHub",
		Percent = -100,
		Prop = "electricity_consumption",
	}),
	PlaceObj('Effect_ModifyLabel', {
		Label = "DroneHub",
		Percent = -100,
		Prop = "maintenance_build_up_per_hr",
	}),
})

PlaceObj('ModItemGameRuleDef', {
	SortKey = 6,
	challenge_mod = -100,
	description = T(670696012911, --[[ModItemGameRuleDef portable-hole description]] "Here, go to Mars, put this hole on the ground, and look inside."),
	display_name = T(541566041555, --[[ModItemGameRuleDef portable-hole display_name]] "Portable Hole"),
	group = "Default",
	id = "portable-hole",
	mod_handle = 7,
	save_in = "Mod/qKwMjRQ",
	PlaceObj('Effect_GrantPrefab', {
		Prefab = "MoholeMine",
	}),
})

PlaceObj('ModItemGameRuleDef', {
	SortKey = 7,
	description = T(259097827152, --[[ModItemGameRuleDef techstrap description]] "Take advantage of simulator research to get a head-start on Martian technology."),
	display_name = T(216587666121, --[[ModItemGameRuleDef techstrap display_name]] "Tech Bootstrap"),
	flavor_text = T(567611163726, --[[ModItemGameRuleDef techstrap flavor_text]] "The simulations may not be entirely accurate, but that doesn't make them useless!"),
	group = "Default",
	id = "techstrap",
	mod_handle = 8,
	save_in = "Mod/qKwMjRQ",
	PlaceObj('Effect_GrantTech', {
		Field = "Biotech",
		Research = "HygroscopicVaporators",
	}),
	PlaceObj('Effect_GrantTech', {
		Field = "Engineering",
		Research = "LowGHighrise",
	}),
	PlaceObj('Effect_GrantTech', {
		Field = "Physics",
		Research = "ExtractorAmplification",
	}),
	PlaceObj('Effect_GrantTech', {
		Field = "Social",
		Research = "EarthMarsInitiative",
	}),
	PlaceObj('Effect_GrantTech', {
		Field = "Terraforming",
		Research = "TerraformingRover",
		comment = "Technically this can't ever show up in slot 1, but I don't want to double up Martian Veg with the sponsor",
	}),
	PlaceObj('Effect_GrantTech', {
		Field = "ReconAndExpansion",
		Research = "LowGShaftDigging",
	}),
	PlaceObj('Effect_TechBoost', {
		Field = "Breakthroughs",
		Percent = -90,
		comment = "temp hack for testing",
	}),
})

